### ISSUE TITLE
deepspeed reference on colab

### ISSUE THREAD

**Issue by huu4ontocord** [princeton-nlp/MeZO#12]
After installing accelerate, deepspeed, transformers and dataset

!MODEL=facebook/opt-1.3b TASK=SST2 MODE=ft LR=1e-5 bash finetune.sh
...
/content/MeZO/large_models/trainer.py:555 in _inner_training_loop            │
│                                                                              │
│   552 │   │   │   │   self.current_flos += float(self.floating_point_ops(inp │
│   553 │   │   │   │                                                          │
│   554 │   │   │   │   # Optimizer step for deepspeed must be called on every │
│ ❱ 555 │   │   │   │   if self.deepspeed:                                     │
│   556 │   │   │   │   │   self.deepspeed.step()                              │
│   557 │   │   │   │                                                          │
│   558 │   │   │   │   if (step + 1) % args.gradient_accumulation_steps == 0  │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'OurTrainer' object has no attribute 'deepspeed'
  0% 0/625 [00:01<?, ?it/s]

**Comment by gaotianyu1350** [comment]
Hi,

It seems to be a problem caused by different transformers versions. You can try upgrading transformers or simply deleting everything related to deepspeed (we do not use the deepspeed package)

**Comment by huu4ontocord** [comment]
thank u
