### ISSUE TITLE
About experimentical setting of  1000 examples

### ISSUE THREAD

**Issue by sglucas** [princeton-nlp/MeZO#14]
Hi,
Thanks for your great work. I would like to ask whether sample 1000 examples is a common setting. I find the training process will be fast and I'm not sure whether this setting is convincing.

Thanks,
Lucas Liu

**Comment by gaotianyu1350** [comment]
Hi Lucas,

Yeah we mainly control the number of examples for efficiency reasons, given that fine-tuning those large models on the original datasets is too costly. I would say the setting is reasonable, as nowadays people focus more and more on few-shot learning or medium-sized dataset fine-tuning. Taking instruction-tuning as an example, [this paper](https://arxiv.org/abs/2305.11206) shows that you only need 1,000 examples.

**Comment by sglucas** [comment]
Hi @gaotianyu1350 

Thanks for your answer!
