### ISSUE TITLE
Cannot reproduce the results of OPT on SST2

### ISSUE THREAD

**Issue by sglucas** [princeton-nlp/MeZO#16]
hi

I try to run the code `MODEL=facebook/opt-13b TASK=SST2 MODE=lora LR=1e-4 EPS=1e-2 bash mezo.sh` and I find the loss cannot converge. I'm not sure whether my current setting is right and I would like to ask whether I need to tune the hyper-parameteers (e.g., lr).

Best,
Lucas

**Comment by sglucas** [comment]
I'm not sure whether the training steps (20k) is too long since I find the loss value can be decreased at first 2k steps and start to increase after that.

**Comment by li2haipeng** [comment]
Ran into the same issue. Launch the example code `MODEL=facebook/opt-13b TASK=SST2 MODE=ft LR=1e-6 EPS=1e-3 bash mezo.sh` without modification and the loss remains almost the same after 20K steps.

**Comment by gaotianyu1350** [comment]
Hi,

Could you specify the pytorch/transformers/accelerate versions you use and also the GPU types? Thanks!

**Comment by li2haipeng** [comment]
Hi,
8x A100 GPUs.  Torch: 2.0.0, accelerate: 0.20.3, transformers: 4.30.2

**Comment by gaotianyu1350** [comment]
Hi,

For a 13B model 1 A100 is enough (though using more shouldn't cause other problems). Can you try our configuration too (torch==2.1.0.dev20230514+cu118, transformers==4.28.1, and accelerate==0.17.1) with one A100 just to rule out other possibilities?

**Comment by sglucas** [comment]
Hi, 

My configuration is

1 A100 GPU, torch 2.0.1, accelerate 0.17.1, transformers 4.28.1.

I will try to upgrade pytorch although I think this may not cause this issue.

**Comment by gaotianyu1350** [comment]
Hi,

Sorry about the inconvenience. I think there is something wrong with the script (probably I accidentally deleted some args when I cleaned the code). I'll figure it out as soon as possible. Stay tuned!

**Comment by gaotianyu1350** [comment]
I agree that PyTorch version shouldn't matter much.

I just reproduce `{'accuracy': 0.8692660550458715, 'dev_accuracy': 0.834}` with the following script (to make it faster i only ran with 1000 steps): 

```bash
MODEL=facebook/opt-13b TASK=SST2 MODE=ft LR=1e-6 EPS=1e-3 STEPS=1000 EVAL_STEPS=500 bash mezo.sh
```

This is to use `accelerate==0.17.1, transformers==4.28.1`

**Comment by sglucas** [comment]
Hi Tianyu, 

Thanks for your reply.

I can also reproduce the result with 1000 training steps. However, when I try to further run the code with more training steps (such as 20k steps, which is similar to the setting in the paper), I find it is difficult to converge and the training loss begin to increase after 5k steps.

**Comment by gaotianyu1350** [comment]
Emm that is weird. Do you happen to have a loss curve to show? I'll also run a 20K one but it might take some time

**Comment by li2haipeng** [comment]
Hi,
I also had the similar observation that the loss decreased first then started increasing after around 1000 steps. Here is the trainer state json file. I trained 16k steps and here only shows the first 2k steps. But you can see the increasing trend of loss and after 16k steps the training loss and eval loss reached 0.74 and 0.67 respectively.
`"log_history": [
    {
      "epoch": 0.16,
      "learning_rate": 1e-06,
      "loss": 0.8569,
      "step": 10
    },
    {
      "epoch": 0.32,
      "learning_rate": 1e-06,
      "loss": 0.8652,
      "step": 20
    },
    {
      "epoch": 0.48,
      "learning_rate": 1e-06,
      "loss": 0.8071,
      "step": 30
    },
    {
      "epoch": 0.63,
      "learning_rate": 1e-06,
      "loss": 0.7789,
      "step": 40
    },
    {
      "epoch": 0.79,
      "learning_rate": 1e-06,
      "loss": 0.8867,
      "step": 50
    },
    {
      "epoch": 0.95,
      "learning_rate": 1e-06,
      "loss": 0.7736,
      "step": 60
    },
    {
      "epoch": 1.11,
      "learning_rate": 1e-06,
      "loss": 0.7373,
      "step": 70
    },
    {
      "epoch": 1.27,
      "learning_rate": 1e-06,
      "loss": 0.7597,
      "step": 80
    },
    {
      "epoch": 1.43,
      "learning_rate": 1e-06,
      "loss": 0.721,
      "step": 90
    },
    {
      "epoch": 1.59,
      "learning_rate": 1e-06,
      "loss": 0.7309,
      "step": 100
    },
    {
      "epoch": 1.75,
      "learning_rate": 1e-06,
      "loss": 0.6313,
      "step": 110
    },
    {
      "epoch": 1.9,
      "learning_rate": 1e-06,
      "loss": 0.7168,
      "step": 120
    },
    {
      "epoch": 2.06,
      "learning_rate": 1e-06,
      "loss": 0.5502,
      "step": 130
    },
    {
      "epoch": 2.22,
      "learning_rate": 1e-06,
      "loss": 0.6083,
      "step": 140
    },
    {
      "epoch": 2.38,
      "learning_rate": 1e-06,
      "loss": 0.6017,
      "step": 150
    },
    {
      "epoch": 2.54,
      "learning_rate": 1e-06,
      "loss": 0.6791,
      "step": 160
    },
    {
      "epoch": 2.7,
      "learning_rate": 1e-06,
      "loss": 0.5808,
      "step": 170
    },
    {
      "epoch": 2.86,
      "learning_rate": 1e-06,
      "loss": 0.5819,
      "step": 180
    },
    {
      "epoch": 3.02,
      "learning_rate": 1e-06,
      "loss": 0.5692,
      "step": 190
    },
    {
      "epoch": 3.17,
      "learning_rate": 1e-06,
      "loss": 0.6399,
      "step": 200
    },
    {
      "epoch": 3.33,
      "learning_rate": 1e-06,
      "loss": 0.5511,
      "step": 210
    },
    {
      "epoch": 3.49,
      "learning_rate": 1e-06,
      "loss": 0.5667,
      "step": 220
    },
    {
      "epoch": 3.65,
      "learning_rate": 1e-06,
      "loss": 0.5702,
      "step": 230
    },
    {
      "epoch": 3.81,
      "learning_rate": 1e-06,
      "loss": 0.5281,
      "step": 240
    },
    {
      "epoch": 3.97,
      "learning_rate": 1e-06,
      "loss": 0.5532,
      "step": 250
    },
    {
      "epoch": 4.13,
      "learning_rate": 1e-06,
      "loss": 0.482,
      "step": 260
    },
    {
      "epoch": 4.29,
      "learning_rate": 1e-06,
      "loss": 0.5402,
      "step": 270
    },
    {
      "epoch": 4.44,
      "learning_rate": 1e-06,
      "loss": 0.6621,
      "step": 280
    },
    {
      "epoch": 4.6,
      "learning_rate": 1e-06,
      "loss": 0.4921,
      "step": 290
    },
    {
      "epoch": 4.76,
      "learning_rate": 1e-06,
      "loss": 0.5293,
      "step": 300
    },
    {
      "epoch": 4.92,
      "learning_rate": 1e-06,
      "loss": 0.545,
      "step": 310
    },
    {
      "epoch": 5.08,
      "learning_rate": 1e-06,
      "loss": 0.5594,
      "step": 320
    },
    {
      "epoch": 5.24,
      "learning_rate": 1e-06,
      "loss": 0.5075,
      "step": 330
    },
    {
      "epoch": 5.4,
      "learning_rate": 1e-06,
      "loss": 0.4753,
      "step": 340
    },
    {
      "epoch": 5.56,
      "learning_rate": 1e-06,
      "loss": 0.4987,
      "step": 350
    },
    {
      "epoch": 5.71,
      "learning_rate": 1e-06,
      "loss": 0.5213,
      "step": 360
    },
    {
      "epoch": 5.87,
      "learning_rate": 1e-06,
      "loss": 0.523,
      "step": 370
    },
    {
      "epoch": 6.03,
      "learning_rate": 1e-06,
      "loss": 0.4545,
      "step": 380
    },
    {
      "epoch": 6.19,
      "learning_rate": 1e-06,
      "loss": 0.4915,
      "step": 390
    },
    {
      "epoch": 6.35,
      "learning_rate": 1e-06,
      "loss": 0.4922,
      "step": 400
    },
    {
      "epoch": 6.51,
      "learning_rate": 1e-06,
      "loss": 0.5237,
      "step": 410
    },
    {
      "epoch": 6.67,
      "learning_rate": 1e-06,
      "loss": 0.4569,
      "step": 420
    },
    {
      "epoch": 6.83,
      "learning_rate": 1e-06,
      "loss": 0.5297,
      "step": 430
    },
    {
      "epoch": 6.98,
      "learning_rate": 1e-06,
      "loss": 0.5212,
      "step": 440
    },
    {
      "epoch": 7.14,
      "learning_rate": 1e-06,
      "loss": 0.5042,
      "step": 450
    },
    {
      "epoch": 7.3,
      "learning_rate": 1e-06,
      "loss": 0.5039,
      "step": 460
    },
    {
      "epoch": 7.46,
      "learning_rate": 1e-06,
      "loss": 0.4864,
      "step": 470
    },
    {
      "epoch": 7.62,
      "learning_rate": 1e-06,
      "loss": 0.5086,
      "step": 480
    },
    {
      "epoch": 7.78,
      "learning_rate": 1e-06,
      "loss": 0.4637,
      "step": 490
    },
    {
      "epoch": 7.94,
      "learning_rate": 1e-06,
      "loss": 0.4776,
      "step": 500
    },
    {
      "epoch": 8.1,
      "learning_rate": 1e-06,
      "loss": 0.5087,
      "step": 510
    },
    {
      "epoch": 8.25,
      "learning_rate": 1e-06,
      "loss": 0.5032,
      "step": 520
    },
    {
      "epoch": 8.41,
      "learning_rate": 1e-06,
      "loss": 0.4333,
      "step": 530
    },
    {
      "epoch": 8.57,
      "learning_rate": 1e-06,
      "loss": 0.4774,
      "step": 540
    },
    {
      "epoch": 8.73,
      "learning_rate": 1e-06,
      "loss": 0.4738,
      "step": 550
    },
    {
      "epoch": 8.89,
      "learning_rate": 1e-06,
      "loss": 0.4859,
      "step": 560
    },
    {
      "epoch": 9.05,
      "learning_rate": 1e-06,
      "loss": 0.5123,
      "step": 570
    },
    {
      "epoch": 9.21,
      "learning_rate": 1e-06,
      "loss": 0.4556,
      "step": 580
    },
    {
      "epoch": 9.37,
      "learning_rate": 1e-06,
      "loss": 0.4968,
      "step": 590
    },
    {
      "epoch": 9.52,
      "learning_rate": 1e-06,
      "loss": 0.4492,
      "step": 600
    },
    {
      "epoch": 9.68,
      "learning_rate": 1e-06,
      "loss": 0.4862,
      "step": 610
    },
    {
      "epoch": 9.84,
      "learning_rate": 1e-06,
      "loss": 0.4177,
      "step": 620
    },
    {
      "epoch": 10.0,
      "learning_rate": 1e-06,
      "loss": 0.4751,
      "step": 630
    },
    {
      "epoch": 10.16,
      "learning_rate": 1e-06,
      "loss": 0.4415,
      "step": 640
    },
    {
      "epoch": 10.32,
      "learning_rate": 1e-06,
      "loss": 0.4906,
      "step": 650
    },
    {
      "epoch": 10.48,
      "learning_rate": 1e-06,
      "loss": 0.3942,
      "step": 660
    },
    {
      "epoch": 10.63,
      "learning_rate": 1e-06,
      "loss": 0.523,
      "step": 670
    },
    {
      "epoch": 10.79,
      "learning_rate": 1e-06,
      "loss": 0.4482,
      "step": 680
    },
    {
      "epoch": 10.95,
      "learning_rate": 1e-06,
      "loss": 0.4137,
      "step": 690
    },
    {
      "epoch": 11.11,
      "learning_rate": 1e-06,
      "loss": 0.4658,
      "step": 700
    },
    {
      "epoch": 11.27,
      "learning_rate": 1e-06,
      "loss": 0.4591,
      "step": 710
    },
    {
      "epoch": 11.43,
      "learning_rate": 1e-06,
      "loss": 0.4203,
      "step": 720
    },
    {
      "epoch": 11.59,
      "learning_rate": 1e-06,
      "loss": 0.4181,
      "step": 730
    },
    {
      "epoch": 11.75,
      "learning_rate": 1e-06,
      "loss": 0.4396,
      "step": 740
    },
    {
      "epoch": 11.9,
      "learning_rate": 1e-06,
      "loss": 0.4426,
      "step": 750
    },
    {
      "epoch": 12.06,
      "learning_rate": 1e-06,
      "loss": 0.4058,
      "step": 760
    },
    {
      "epoch": 12.22,
      "learning_rate": 1e-06,
      "loss": 0.4194,
      "step": 770
    },
    {
      "epoch": 12.38,
      "learning_rate": 1e-06,
      "loss": 0.5052,
      "step": 780
    },
    {
      "epoch": 12.54,
      "learning_rate": 1e-06,
      "loss": 0.4237,
      "step": 790
    },
    {
      "epoch": 12.7,
      "learning_rate": 1e-06,
      "loss": 0.4322,
      "step": 800
    },
    {
      "epoch": 12.86,
      "learning_rate": 1e-06,
      "loss": 0.4369,
      "step": 810
    },
    {
      "epoch": 13.02,
      "learning_rate": 1e-06,
      "loss": 0.456,
      "step": 820
    },
    {
      "epoch": 13.17,
      "learning_rate": 1e-06,
      "loss": 0.3824,
      "step": 830
    },
    {
      "epoch": 13.33,
      "learning_rate": 1e-06,
      "loss": 0.3969,
      "step": 840
    },
    {
      "epoch": 13.49,
      "learning_rate": 1e-06,
      "loss": 0.4602,
      "step": 850
    },
    {
      "epoch": 13.65,
      "learning_rate": 1e-06,
      "loss": 0.4563,
      "step": 860
    },
    {
      "epoch": 13.81,
      "learning_rate": 1e-06,
      "loss": 0.468,
      "step": 870
    },
    {
      "epoch": 13.97,
      "learning_rate": 1e-06,
      "loss": 0.3304,
      "step": 880
    },
    {
      "epoch": 14.13,
      "learning_rate": 1e-06,
      "loss": 0.4061,
      "step": 890
    },
    {
      "epoch": 14.29,
      "learning_rate": 1e-06,
      "loss": 0.4224,
      "step": 900
    },
    {
      "epoch": 14.44,
      "learning_rate": 1e-06,
      "loss": 0.416,
      "step": 910
    },
    {
      "epoch": 14.6,
      "learning_rate": 1e-06,
      "loss": 0.3737,
      "step": 920
    },
    {
      "epoch": 14.76,
      "learning_rate": 1e-06,
      "loss": 0.385,
      "step": 930
    },
    {
      "epoch": 14.92,
      "learning_rate": 1e-06,
      "loss": 0.4101,
      "step": 940
    },
    {
      "epoch": 15.08,
      "learning_rate": 1e-06,
      "loss": 0.4967,
      "step": 950
    },
    {
      "epoch": 15.24,
      "learning_rate": 1e-06,
      "loss": 0.4181,
      "step": 960
    },
    {
      "epoch": 15.4,
      "learning_rate": 1e-06,
      "loss": 0.4386,
      "step": 970
    },
    {
      "epoch": 15.56,
      "learning_rate": 1e-06,
      "loss": 0.4132,
      "step": 980
    },
    {
      "epoch": 15.71,
      "learning_rate": 1e-06,
      "loss": 0.4531,
      "step": 990
    },
    {
      "epoch": 15.87,
      "learning_rate": 1e-06,
      "loss": 0.3857,
      "step": 1000
    },
    {
      "epoch": 16.03,
      "learning_rate": 1e-06,
      "loss": 0.4262,
      "step": 1010
    },
    {
      "epoch": 16.19,
      "learning_rate": 1e-06,
      "loss": 0.4625,
      "step": 1020
    },
    {
      "epoch": 16.35,
      "learning_rate": 1e-06,
      "loss": 0.4121,
      "step": 1030
    },
    {
      "epoch": 16.51,
      "learning_rate": 1e-06,
      "loss": 0.3961,
      "step": 1040
    },
    {
      "epoch": 16.67,
      "learning_rate": 1e-06,
      "loss": 0.4214,
      "step": 1050
    },
    {
      "epoch": 16.83,
      "learning_rate": 1e-06,
      "loss": 0.4028,
      "step": 1060
    },
    {
      "epoch": 16.98,
      "learning_rate": 1e-06,
      "loss": 0.4288,
      "step": 1070
    },
    {
      "epoch": 17.14,
      "learning_rate": 1e-06,
      "loss": 0.4578,
      "step": 1080
    },
    {
      "epoch": 17.3,
      "learning_rate": 1e-06,
      "loss": 0.3882,
      "step": 1090
    },
    {
      "epoch": 17.46,
      "learning_rate": 1e-06,
      "loss": 0.4009,
      "step": 1100
    },
    {
      "epoch": 17.62,
      "learning_rate": 1e-06,
      "loss": 0.4281,
      "step": 1110
    },
    {
      "epoch": 17.78,
      "learning_rate": 1e-06,
      "loss": 0.4033,
      "step": 1120
    },
    {
      "epoch": 17.94,
      "learning_rate": 1e-06,
      "loss": 0.4047,
      "step": 1130
    },
    {
      "epoch": 18.1,
      "learning_rate": 1e-06,
      "loss": 0.3847,
      "step": 1140
    },
    {
      "epoch": 18.25,
      "learning_rate": 1e-06,
      "loss": 0.3811,
      "step": 1150
    },
    {
      "epoch": 18.41,
      "learning_rate": 1e-06,
      "loss": 0.411,
      "step": 1160
    },
    {
      "epoch": 18.57,
      "learning_rate": 1e-06,
      "loss": 0.4268,
      "step": 1170
    },
    {
      "epoch": 18.73,
      "learning_rate": 1e-06,
      "loss": 0.4798,
      "step": 1180
    },
    {
      "epoch": 18.89,
      "learning_rate": 1e-06,
      "loss": 0.3543,
      "step": 1190
    },
    {
      "epoch": 19.05,
      "learning_rate": 1e-06,
      "loss": 0.4105,
      "step": 1200
    },
    {
      "epoch": 19.21,
      "learning_rate": 1e-06,
      "loss": 0.3923,
      "step": 1210
    },
    {
      "epoch": 19.37,
      "learning_rate": 1e-06,
      "loss": 0.3799,
      "step": 1220
    },
    {
      "epoch": 19.52,
      "learning_rate": 1e-06,
      "loss": 0.368,
      "step": 1230
    },
    {
      "epoch": 19.68,
      "learning_rate": 1e-06,
      "loss": 0.4855,
      "step": 1240
    },
    {
      "epoch": 19.84,
      "learning_rate": 1e-06,
      "loss": 0.3887,
      "step": 1250
    },
    {
      "epoch": 20.0,
      "learning_rate": 1e-06,
      "loss": 0.4284,
      "step": 1260
    },
    {
      "epoch": 20.16,
      "learning_rate": 1e-06,
      "loss": 0.3796,
      "step": 1270
    },
    {
      "epoch": 20.32,
      "learning_rate": 1e-06,
      "loss": 0.4605,
      "step": 1280
    },
    {
      "epoch": 20.48,
      "learning_rate": 1e-06,
      "loss": 0.3761,
      "step": 1290
    },
    {
      "epoch": 20.63,
      "learning_rate": 1e-06,
      "loss": 0.3893,
      "step": 1300
    },
    {
      "epoch": 20.79,
      "learning_rate": 1e-06,
      "loss": 0.4208,
      "step": 1310
    },
    {
      "epoch": 20.95,
      "learning_rate": 1e-06,
      "loss": 0.3397,
      "step": 1320
    },
    {
      "epoch": 21.11,
      "learning_rate": 1e-06,
      "loss": 0.3532,
      "step": 1330
    },
    {
      "epoch": 21.27,
      "learning_rate": 1e-06,
      "loss": 0.4305,
      "step": 1340
    },
    {
      "epoch": 21.43,
      "learning_rate": 1e-06,
      "loss": 0.3444,
      "step": 1350
    },
    {
      "epoch": 21.59,
      "learning_rate": 1e-06,
      "loss": 0.3933,
      "step": 1360
    },
    {
      "epoch": 21.75,
      "learning_rate": 1e-06,
      "loss": 0.4275,
      "step": 1370
    },
    {
      "epoch": 21.9,
      "learning_rate": 1e-06,
      "loss": 0.3967,
      "step": 1380
    },
    {
      "epoch": 22.06,
      "learning_rate": 1e-06,
      "loss": 0.3525,
      "step": 1390
    },
    {
      "epoch": 22.22,
      "learning_rate": 1e-06,
      "loss": 0.346,
      "step": 1400
    },
    {
      "epoch": 22.38,
      "learning_rate": 1e-06,
      "loss": 0.431,
      "step": 1410
    },
    {
      "epoch": 22.54,
      "learning_rate": 1e-06,
      "loss": 0.4314,
      "step": 1420
    },
    {
      "epoch": 22.7,
      "learning_rate": 1e-06,
      "loss": 0.4208,
      "step": 1430
    },
    {
      "epoch": 22.86,
      "learning_rate": 1e-06,
      "loss": 0.3458,
      "step": 1440
    },
    {
      "epoch": 23.02,
      "learning_rate": 1e-06,
      "loss": 0.4213,
      "step": 1450
    },
    {
      "epoch": 23.17,
      "learning_rate": 1e-06,
      "loss": 0.3574,
      "step": 1460
    },
    {
      "epoch": 23.33,
      "learning_rate": 1e-06,
      "loss": 0.4057,
      "step": 1470
    },
    {
      "epoch": 23.49,
      "learning_rate": 1e-06,
      "loss": 0.3236,
      "step": 1480
    },
    {
      "epoch": 23.65,
      "learning_rate": 1e-06,
      "loss": 0.3996,
      "step": 1490
    },
    {
      "epoch": 23.81,
      "learning_rate": 1e-06,
      "loss": 0.4169,
      "step": 1500
    },
    {
      "epoch": 23.97,
      "learning_rate": 1e-06,
      "loss": 0.4469,
      "step": 1510
    },
    {
      "epoch": 24.13,
      "learning_rate": 1e-06,
      "loss": 0.3913,
      "step": 1520
    },
    {
      "epoch": 24.29,
      "learning_rate": 1e-06,
      "loss": 0.3659,
      "step": 1530
    },
    {
      "epoch": 24.44,
      "learning_rate": 1e-06,
      "loss": 0.428,
      "step": 1540
    },
    {
      "epoch": 24.6,
      "learning_rate": 1e-06,
      "loss": 0.4358,
      "step": 1550
    },
    {
      "epoch": 24.76,
      "learning_rate": 1e-06,
      "loss": 0.3848,
      "step": 1560
    },
    {
      "epoch": 24.92,
      "learning_rate": 1e-06,
      "loss": 0.379,
      "step": 1570
    },
    {
      "epoch": 25.08,
      "learning_rate": 1e-06,
      "loss": 0.404,
      "step": 1580
    },
    {
      "epoch": 25.24,
      "learning_rate": 1e-06,
      "loss": 0.499,
      "step": 1590
    },
    {
      "epoch": 25.4,
      "learning_rate": 1e-06,
      "loss": 0.3982,
      "step": 1600
    },
    {
      "epoch": 25.56,
      "learning_rate": 1e-06,
      "loss": 0.4151,
      "step": 1610
    },
    {
      "epoch": 25.71,
      "learning_rate": 1e-06,
      "loss": 0.3869,
      "step": 1620
    },
    {
      "epoch": 25.87,
      "learning_rate": 1e-06,
      "loss": 0.3685,
      "step": 1630
    },
    {
      "epoch": 26.03,
      "learning_rate": 1e-06,
      "loss": 0.3828,
      "step": 1640
    },
    {
      "epoch": 26.19,
      "learning_rate": 1e-06,
      "loss": 0.4284,
      "step": 1650
    },
    {
      "epoch": 26.35,
      "learning_rate": 1e-06,
      "loss": 0.371,
      "step": 1660
    },
    {
      "epoch": 26.51,
      "learning_rate": 1e-06,
      "loss": 0.4344,
      "step": 1670
    },
    {
      "epoch": 26.67,
      "learning_rate": 1e-06,
      "loss": 0.4655,
      "step": 1680
    },
    {
      "epoch": 26.83,
      "learning_rate": 1e-06,
      "loss": 0.4248,
      "step": 1690
    },
    {
      "epoch": 26.98,
      "learning_rate": 1e-06,
      "loss": 0.3962,
      "step": 1700
    },
    {
      "epoch": 27.14,
      "learning_rate": 1e-06,
      "loss": 0.4505,
      "step": 1710
    },
    {
      "epoch": 27.3,
      "learning_rate": 1e-06,
      "loss": 0.3429,
      "step": 1720
    },
    {
      "epoch": 27.46,
      "learning_rate": 1e-06,
      "loss": 0.4982,
      "step": 1730
    },
    {
      "epoch": 27.62,
      "learning_rate": 1e-06,
      "loss": 0.4268,
      "step": 1740
    },
    {
      "epoch": 27.78,
      "learning_rate": 1e-06,
      "loss": 0.5096,
      "step": 1750
    },
    {
      "epoch": 27.94,
      "learning_rate": 1e-06,
      "loss": 0.4845,
      "step": 1760
    },
    {
      "epoch": 28.1,
      "learning_rate": 1e-06,
      "loss": 0.4307,
      "step": 1770
    },
    {
      "epoch": 28.25,
      "learning_rate": 1e-06,
      "loss": 0.3939,
      "step": 1780
    },
    {
      "epoch": 28.41,
      "learning_rate": 1e-06,
      "loss": 0.4545,
      "step": 1790
    },
    {
      "epoch": 28.57,
      "learning_rate": 1e-06,
      "loss": 0.4404,
      "step": 1800
    },
    {
      "epoch": 28.73,
      "learning_rate": 1e-06,
      "loss": 0.4639,
      "step": 1810
    },
    {
      "epoch": 28.89,
      "learning_rate": 1e-06,
      "loss": 0.4602,
      "step": 1820
    },
    {
      "epoch": 29.05,
      "learning_rate": 1e-06,
      "loss": 0.5972,
      "step": 1830
    },
    {
      "epoch": 29.21,
      "learning_rate": 1e-06,
      "loss": 0.5339,
      "step": 1840
    },
    {
      "epoch": 29.37,
      "learning_rate": 1e-06,
      "loss": 0.4926,
      "step": 1850
    },
    {
      "epoch": 29.52,
      "learning_rate": 1e-06,
      "loss": 0.5364,
      "step": 1860
    },
    {
      "epoch": 29.68,
      "learning_rate": 1e-06,
      "loss": 0.4847,
      "step": 1870
    },
    {
      "epoch": 29.84,
      "learning_rate": 1e-06,
      "loss": 0.5075,
      "step": 1880
    },
    {
      "epoch": 30.0,
      "learning_rate": 1e-06,
      "loss": 0.5225,
      "step": 1890
    },
    {
      "epoch": 30.16,
      "learning_rate": 1e-06,
      "loss": 0.5339,
      "step": 1900
    },
    {
      "epoch": 30.32,
      "learning_rate": 1e-06,
      "loss": 0.4113,
      "step": 1910
    },
    {
      "epoch": 30.48,
      "learning_rate": 1e-06,
      "loss": 0.4421,
      "step": 1920
    },
    {
      "epoch": 30.63,
      "learning_rate": 1e-06,
      "loss": 0.5245,
      "step": 1930
    },
    {
      "epoch": 30.79,
      "learning_rate": 1e-06,
      "loss": 0.5536,
      "step": 1940
    },
    {
      "epoch": 30.95,
      "learning_rate": 1e-06,
      "loss": 0.5192,
      "step": 1950
    },
    {
      "epoch": 31.11,
      "learning_rate": 1e-06,
      "loss": 0.5384,
      "step": 1960
    },
    {
      "epoch": 31.27,
      "learning_rate": 1e-06,
      "loss": 0.5093,
      "step": 1970
    },
    {
      "epoch": 31.43,
      "learning_rate": 1e-06,
      "loss": 0.4807,
      "step": 1980
    },
    {
      "epoch": 31.59,
      "learning_rate": 1e-06,
      "loss": 0.5337,
      "step": 1990
    },
    {
      "epoch": 31.75,
      "learning_rate": 1e-06,
      "loss": 0.576,
      "step": 2000
    },
    {
      "epoch": 31.9,
      "learning_rate": 1e-06,
      "loss": 0.5768,
      "step": 2010`

**Comment by sglucas** [comment]
I think maybe we need a schedule for the learning rate.

**Comment by gaotianyu1350** [comment]
Sorry my bad. I realized the problem. In our experiment we used lr=1e-7 / eps=1e-3, and you should be able to get roughly acc=0.9140. We did mention in Table 14 that we do a lr=1e-6/1e-7 grid search for OPT experiments, but this is a good catch as I shouldn't use this as an example in README.

**Comment by gaotianyu1350** [comment]
The readme is updated! Check it out

**Comment by sglucas** [comment]
Hi Tianyu,

Thanks for your great work and kind help. I'll have a try with the new learning rate.
