### ISSUE TITLE
AttributeError: 'TrainingArguments' object has no attribute 'linear_probing'

### ISSUE THREAD

**Issue by thistleknot** [princeton-nlp/MeZO#18]
(env-MeZo) [root@pve-m7330 TrainLLMv2]# python mezo.py
Traceback (most recent call last):
  File "/home/user/TrainLLMv2/mezo.py", line 71, in <module>
    trainer.train()
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TrainLLMv2/functions.py", line 17, in _inner_training_loop
    if self.args.linear_probing:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingArguments' object has no attribute 'linear_probing'

I attempted to integrate this

One thing that stands out to me.

![image](https://github.com/princeton-nlp/MeZO/assets/5154106/7fc3f3ff-26b7-4bab-b93a-259e24645e54)

Why so much difference between the medium and large trianer.py, if it's 'only a few lines of changes'.

I opted for the large_model (because I wanted to train eventually 7b).  I essentially pulled this class in 
https://gist.github.com/thistleknot/6c0349c29e81c71cb547574666918c01 and called it MeZOTrainer

and imported all the same statements you had in your original large_models trainer.py (i.e. everything above the class definition), and then one by one started to pull in additional imports (for ex, logger was missing, inspect wasn't defined).

But i'm at a loss for how to addressed this linear_probing.

so now I have to dig in to the code and figure what else I need to patch in

https://github.com/princeton-nlp/MeZO/blob/main/large_models/run.py

**Comment by gaotianyu1350** [comment]
Our trainer was modified to do some of the controlled experiments (for example, linear probing is for our experiments and very likely you don't need it at all). My suggestion is to pull the trainer of your Huggingface transformers' version, and follow the README and inject the highlighted code there.

**Comment by thistleknot** [comment]
That's exactly what i did. The linear probing was part of the changes your
mezo added said I needed to incorporate. (you can see the full implementation here: https://github.com/princeton-nlp/MeZO/issues/8)

**Comment by gaotianyu1350** [comment]
Sorry about that. The linear probing part should be ignored. I updated the readme.

**Comment by thistleknot** [comment]
thanks, that did it (on to the next error!)
