### ISSUE TITLE
Can you provide more details about how to run the code?

### ISSUE THREAD

**Issue by kiseliu** [princeton-nlp/MeZO#5]
Thanks for opening the source codes. 
However, I am confused about how to run the codes. Here are two questions:
1. The [README.md](https://github.com/princeton-nlp/MeZO/blob/main/README.md) file says that to reproduce the OPT experiments, please refer to the `large_models` folder. 
However, I find some bash examples to train opt models in the `medium_models` folder.

2. Yes, maybe opt-125m is a medium model, but there will have an error to train the opt-125m model under the **medium_models** folder:
    I set the template be "`*cls**sent_0*_It_was*mask*.*sep+*`" on SST-2 task. 
    There will generate None token in `new_tokens` from line 112 to line 204 of `medium_models/src/dataset.py`.
    ```
    116                if (part == 'cls' or part == 'bos') and ('T5' in type(tokenizer).__name__ or tokenizer.model_type == "gpt2"):
    117                     # T5 or GPT-2 do not have cls token
    118                     continue
    ```
    The opt models also don't have cls token, this will cause an error.

    Maybe I use a wrong template, so can you provide more details about this project. Thanks.

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for your interest in our repo! We just updated the large_models README and check it out!
