### ISSUE TITLE
MeZO running script for roberta-large is not working

### ISSUE THREAD

**Issue by sanyalsunny111** [princeton-nlp/MeZO#9]
Hi @sadhikamalladi @gaotianyu1350 ,

Very interesting work, I am trying to reproduce your MeZO results for roberta large model using SST-2 could you please provide me a running script to run this experiment.  Below is what I did and got some error with args.

python medium_models/run.py --zero_order_optim --efficient_zero_order --model_name_or_path roberta-large --task_name SST-2 --data_dir ./data/original/SST-2 --output_dir output

![image](https://github.com/princeton-nlp/MeZO/assets/36811567/d39f57a0-18d2-4548-93cf-409ee0ed64f1)

**Comment by gaotianyu1350** [comment]
Hi,

We have an example script in the README and that might be easier to use than directly running run.py. I copied it here: 

```bash
# Adam fine-tuning
TASK=SST-2 K=16 SEED=42 BS=8 LR=1e-5 MODEL=roberta-large bash finetune.sh

# Adam fine-tuning + prefix-tuning
TASK=SST-2 K=16 SEED=42 BS=8 LR=1e-2 MODEL=roberta-large EXTRA_TAG=prefix bash finetune.sh --prefix_tuning --num_prefix 5 --no_reparam --prefix_init_by_real_act

# Adam fine-tuning + LoRA
TASK=SST-2 K=16 SEED=42 BS=8 LR=1e-4 MODEL=roberta-large EXTRA_TAG=lora bash finetune.sh --apply_lora --lora_r 8 --lora_alpha 16

# MeZO
TASK=SST-2 K=16 SEED=42 BS=64 LR=1e-6 EPS=1e-3 MODEL=roberta-large bash mezo.sh

# MeZO + prefix-tuning
TASK=SST-2 K=16 SEED=42 BS=64 LR=1e-2 EPS=1e-1 MODEL=roberta-large EXTRA_TAG=prefix bash mezo.sh --prefix_tuning --num_prefix 5 --no_reparam --prefix_init_by_real_act

# MeZO + LoRA
TASK=SST-2 K=16 SEED=42 BS=64 LR=1e-4 EPS=1e-3 MODEL=roberta-large EXTRA_TAG=lora bash mezo.sh --apply_lora --lora_r 8 --lora_alpha 16

```
